environment:

  global:
    # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
    # /E:ON and /V:ON options are not enabled in the batch script intepreter
    # See: http://stackoverflow.com/a/13751649/163740
    CMD_IN_ENV: "cmd /E:ON /V:ON /C .\\appveyor\\run_with_env.cmd"
    BINSTAR_USER: jlaura

  PYTHON_VERSION: 3.4
   
platform:
   - x64

install:
   - cmd: set PATH=C:\Miniconda3;C:\Miniconda3\Scripts;%PATH%
   - cmd: conda config --set always_yes yes --set changeps1 no
   - cmd: conda update -q conda

   # Useful for debugging any issues with conda
   - cmd: conda info -a

   # Install not using env because build needs to be in root env
   - cmd: conda config --add channels jlaura

   # Development installation
   - cmd: conda install anaconda-client

build: off

after_test:
   # After test success, package and upload to Anaconda
   - "%CMD_IN_ENV% python ci_tools/condaci.py build conda/"
