environment:
  # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
  # /E:ON and /V:ON options are not enabled in the batch script interpreter
  # See: http://stackoverflow.com/a/13751649/163740
  CMD_IN_ENV: "cmd /E:ON /V:ON /C obvci_appveyor_python_build_env.cmd"
  BINSTAR_USER: jlaura

matrix:
   - PYTHON_VERSION: 3.4
     TARGET_ARCH: "x64"
     CONDA_INSTALL_LOCN: "C:\\Miniconda3-x64"

   - PYTHON_VERSION: 2.7
     TARGET_ARCH: "x64"
     CONDA_INSTALL_LOCN: "C:\\Miniconda-x64

platform:
   - x64

install:
   - cmd: set "PATH=%CONDA_INSTALL_LOCN%\\Scripts;%CONDA_INSTALL_LOCN%\\Library\\bin;%PATH%"
   - cmd: conda config --set always_yes yes --set changeps1 no
   - cmd: conda update --yes --quiet conda
   # Useful for debugging any issues with conda
   - cmd: conda info -a

   # Install not using env because build needs to be in root env
   - cmd: conda config --add channels jlaura

   # Development installation
   - cmd: conda install anaconda-client

build: off

deploy_script:
   # After test success, package and upload to Anaconda
   - 'python ci_tools/condaci.py build .\conda'
